# Generated by Django 5.0.1 on 2026-01-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('PAID', 'Paid Leave'),
                    ('SICK', 'Sick Leave'),
                    ('UNPAID', 'Unpaid Leave'),
                    ('CASUAL', 'Casual Leave'),
                ],
            ),
        ),
    ]
