# Generated by Django 6.0 on 2026-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_proofs/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/resumes/'),
        ),
    ]
