# Generated by Django 6.0 on 2026-01-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeeprofile_id_proof_employeeprofile_resume'),
    ]

    operations = [
    ]
